# Generated by Django 4.0.5 on 2022-06-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='walletAddress',
            new_name='wallet_address',
        ),
    ]
