# Generated by Django 4.0.5 on 2022-06-11 17:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_walletaddress_profile_wallet_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('open', 'Open Bounty'), ('work_started', 'Work Started'), ('work_submitted', 'Work Submitted'), ('done', 'Done'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='open', max_length=50)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, default='')),
                ('funding_organization', models.CharField(blank=True, default='', max_length=255)),
                ('organization_url', models.CharField(blank=True, default='', max_length=255)),
                ('attached_job_url', models.URLField(blank=True, db_index=True, null=True)),
                ('ways_to_contact', models.CharField(blank=True, default='', max_length=255)),
                ('image_attachments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this bounty is featured')),
                ('bounty_type', models.CharField(blank=True, choices=[('Bug', 'Bug'), ('Project', 'Project'), ('Feature', 'Feature'), ('Security', 'Security'), ('Improvement', 'Improvement'), ('Design', 'Design'), ('Docs', 'Docs'), ('Code review', 'Code review'), ('Other', 'Other')], db_index=True, max_length=50)),
                ('project_length', models.CharField(blank=True, choices=[('Hours', 'Hours'), ('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months')], db_index=True, max_length=50)),
                ('bounty_category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend'), ('design', 'design'), ('documentation', 'documentation'), ('other', 'other'), ('react', 'react'), ('solidity', 'solidity'), ('javascript', 'javascript')], max_length=50), blank=True, default=list, size=None)),
                ('bounty_value_in_eth', models.DecimalField(decimal_places=10, help_text='The amount in eth users bounty creators want to pay out for the bounty', max_digits=50)),
                ('bounty_value_in_usd', models.DecimalField(decimal_places=2, help_text='The amount in usd users bounty creators want to pay out for the bounty', max_digits=100)),
                ('repo_type', models.CharField(choices=[('public', 'public')], default='public', max_length=10)),
                ('permission_type', models.CharField(choices=[('permissionless', 'permissionless'), ('approval', 'approval')], db_index=True, default='permissionless', max_length=50)),
                ('project_type', models.CharField(choices=[('traditional', 'traditional')], db_index=True, default='traditional', max_length=50)),
                ('attached_job_description', models.URLField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('cancelled', 'cancelled'), ('done', 'done'), ('expired', 'expired'), ('reserved', 'reserved'), ('open', 'open'), ('started', 'started'), ('submitted', 'submitted')], db_index=True, default='open', max_length=50)),
                ('experience_level', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], db_index=True, max_length=50)),
                ('accepted', models.BooleanField(default=False, help_text='Whether the bounty has been done')),
                ('canceled_on', models.DateTimeField(blank=True, null=True)),
                ('canceled_bounty_reason', models.TextField(blank=True, default='', verbose_name='Cancelation reason')),
                ('bounty_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty_created', to='app.profile')),
                ('bounty_owner_profile', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty_assigned', to='app.profile')),
                ('other_owners', models.ManyToManyField(blank=True, to='app.profile')),
            ],
        ),
    ]
