# Generated by Django 4.0.5 on 2022-06-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_bounty_attached_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bounty',
            name='bounty_owner_profile',
        ),
        migrations.AddField(
            model_name='bounty',
            name='bounty_owner_wallet',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='bounty_creator',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
