# Generated by Django 4.0.5 on 2022-06-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_bounty_bounty_owner_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='bounty_owner_wallet',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='canceled_bounty_reason',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Cancelation reason'),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], db_index=True, default='beginner', max_length=50),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='other_owners',
            field=models.ManyToManyField(blank=True, default=None, to='app.profile'),
        ),
    ]
