# Generated by Django 4.0.5 on 2022-06-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_bounty_image_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='image_attachments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
