# Generated by Django 4.0.5 on 2022-06-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_bounty_owner_wallets_bounty_bounty_owner_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Bounty Created', 'Bounty Created'), ('Started Work', 'Started Work'), ('Work Submitted', 'Work Submitted'), ('Work Approved', 'Work Approved'), ('Funds Paid Out', 'Funds Paid Out')], max_length=100),
        ),
    ]
