# Generated by Django 4.0.5 on 2022-06-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Bounty Created', 'Bounty Created'), ('Started Work', 'Started Work'), ('Work Submitted', 'Work Submitted'), ('Work Approved', 'Work Approved'), ('Funds Paid Out', 'Funds Paid Out'), ('Left Project', 'Left Project')], max_length=100),
        ),
    ]
