# Generated by Django 4.0.5 on 2022-06-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_profile_link_worksubmission_project_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksubmission',
            name='project_link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
