# Generated by Django 4.0.5 on 2022-06-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_worksubmission_submission_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksubmission',
            name='archived',
            field=models.BooleanField(default=False, help_text='For organizing when looking at submissions'),
        ),
    ]
