# Generated by Django 4.0.5 on 2022-07-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_remove_organization_members_organization_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_profile_picture_inital',
            field=models.CharField(default='#fb1c48', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
