# Generated by Django 4.0.5 on 2022-07-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_organization_organization_profile_picture_inital_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='organization_profile_picture_inital',
            new_name='organization_profile_picture_initial',
        ),
    ]
