# Generated by Django 4.0.5 on 2022-07-09 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_transactionintoescrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionintoescrow',
            name='bounty',
        ),
        migrations.AlterField(
            model_name='bounty',
            name='bounty_type',
            field=models.CharField(blank=True, choices=[('Bug', 'Bug'), ('Feature Request', 'Feature Request'), ('Security', 'Security'), ('Improvement', 'Improvement'), ('Design', 'Design'), ('Docs', 'Docs'), ('Code review', 'Code review'), ('Good first issue', 'Good first issue'), ('Other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='FundBounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('TransactionIntoEscrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transactionintoescrow')),
                ('bounty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bounty')),
            ],
        ),
    ]
