# Generated by Django 4.0.5 on 2022-07-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_worksubmission_updated_at_backingbounty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='bounty_type',
            field=models.CharField(blank=True, choices=[('Bug', 'Bug'), ('Feature Request', 'Feature Request'), ('Security', 'Security'), ('Improvement', 'Improvement'), ('Design', 'Design'), ('Docs', 'Docs'), ('Code review', 'Code review'), ('Good first issue', 'Good first issue'), ('Other', 'Other')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='bounty_value_in_usd',
            field=models.DecimalField(decimal_places=2, help_text='The amount in usd users bounty creators want to pay out for the bounty', max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='project_length',
            field=models.CharField(blank=True, choices=[('Hours', 'Hours'), ('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months')], db_index=True, max_length=50, null=True),
        ),
    ]
