# Generated by Django 4.0.5 on 2022-07-12 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_bounty_bounty_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundbounty',
            old_name='TransactionIntoEscrow',
            new_name='transaction_into_escrow',
        ),
    ]
