# Generated by Django 4.0.5 on 2022-07-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_rename_transactionintoescrow_fundbounty_transaction_into_escrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionintoescrow',
            name='description',
            field=models.TextField(),
        ),
    ]
