# Generated by Django 4.0.5 on 2022-07-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_transactionintoescrow_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
