# Generated by Django 4.0.5 on 2022-07-13 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_rename_profile_bounty_creator_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembers',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
        migrations.AlterField(
            model_name='organizationmembers',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
