# Generated by Django 4.0.5 on 2022-07-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='external_url_of_requests',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
