# Generated by Django 4.0.5 on 2022-07-18 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_stripeaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeaccount',
            name='account_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripeaccount',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripeaccount',
            name='stripe_account_id',
            field=models.CharField(db_index=True, default='acct_18F8PgIXTelxpQan', max_length=255),
            preserve_default=False,
        ),
    ]
