# Generated by Django 4.0.5 on 2022-07-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_fundingtransaction_remove_fundbounty_bounty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bounty',
            name='bounty_creator',
        ),
    ]
