# Generated by Django 4.0.5 on 2022-06-13 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bounty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bounty',
            name='attached_job_description',
        ),
    ]
