# Generated by Django 4.0.5 on 2022-06-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_bounty_bounty_owner_wallets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bounty',
            name='bounty_owner_wallet',
        ),
    ]
