# Generated by Django 4.0.5 on 2022-06-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_activity_activity_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksubmission',
            old_name='profile_link',
            new_name='project_link',
        ),
        migrations.AddField(
            model_name='worksubmission',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
