# Generated by Django 4.0.5 on 2022-06-15 22:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_worksubmission_project_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funderrating',
            name='profile',
        ),
        migrations.AddField(
            model_name='funderrating',
            name='rating_creator',
            field=models.ForeignKey(default=1, help_text='Profile creating the rating', on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='app.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funderrating',
            name='rating_receiver',
            field=models.ForeignKey(default=1, help_text='Profile receiving the rating', on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='app.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funderrating',
            name='star_rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
