# Generated by Django 4.0.5 on 2022-06-15 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_funderrating_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funderrating',
            name='rating_creator',
            field=models.ForeignKey(default=None, help_text='Profile creating the rating', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_id', to='app.profile'),
        ),
        migrations.AlterField(
            model_name='funderrating',
            name='rating_receiver',
            field=models.ForeignKey(default=None, help_text='Profile receiving the rating', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_id', to='app.profile'),
        ),
    ]
