# Generated by Django 4.0.5 on 2022-06-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_funderrating_rating_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksubmission',
            name='submission_header',
            field=models.CharField(default='', max_length=255),
        ),
    ]
