# Generated by Django 4.0.5 on 2022-06-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_worksubmission_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksubmission',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='worksubmission',
            name='rejected',
        ),
        migrations.AddField(
            model_name='worksubmission',
            name='open',
            field=models.BooleanField(default=True, help_text='For organizing when looking at submissions'),
        ),
    ]
