# Generated by Django 4.0.5 on 2022-06-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallet_address',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
